from jidutest_can.can.tools.bit_timing import BitTimingFd


TOSUNCANFD_500000_2000000 = BitTimingFd(80000000, 1, 63, 16, 15, 2, 7, 2, 2)
TOSUN_VID = 0x5453
ERROR_CODE = {
    1: "Index out of range",
    2: "Connect failed",
    3: "Device not found",
    4: "Error code not valid",
    5: "HID device already connected",
    6: "HID write data failed",
    7: "HID read data failed",
    8: "HID TX buffer overrun",
    9: "HID TX buffer too large",
    10: "HID RX packet report ID invalid",
    11: "HID RX packet length invalid",
    12: "Internal test failed",
    13: "RX packet lost",
    14: "SetupDiGetDeviceInterfaceDetai",
    15: "Create file failed",
    16: "CreateFile failed for read handle",
    17: "CreateFile failed for write handle",
    18: "HidD_SetNumInputBuffers",
    19: "HidD_GetPreparsedData",
    20: "HidP_GetCaps",
    21: "WriteFile",
    22: "GetOverlappedResult",
    23: "HidD_SetFeature",
    24: "HidD_GetFeature",
    25: "Send Feature Report DeviceIoContro",
    26: "Send Feature Report GetOverLappedResult",
    27: "HidD_GetManufacturerString",
    28: "HidD_GetProductString",
    29: "HidD_GetSerialNumberString",
    30: "HidD_GetIndexedString",
    31: "Transmit timed out",
    32: "HW DFU flash write failed",
    33: "HW DFU write without erase",
    34: "HW DFU crc check error",
    35: "HW DFU reset before crc check success",
    36: "HW packet identifier invalid",
    37: "HW packet length invalid",
    38: "HW internal test failed",
    39: "HW rx from pc packet lost",
    40: "HW tx to pc buffer overrun",
    41: "HW API parameter invalid",
    42: "DFU file load failed",
    43: "DFU header write failed",
    44: "Read status timed out",
    45: "Callback already exists",
    46: "Callback not exists",
    47: "File corrupted or not recognized",
    48: "Database unique id not found",
    49: "Software API parameter invalid",
    50: "Software API generic timed out",
    51: "Software API set hw config. failed",
    52: "Index out of bounds",
    53: "RX wait timed out",
    54: "Get I/O failed",
    55: "Set I/O failed",
    56: "An active replay is already running",
    57: "Instance not exists",
    58: "CAN message transmit failed",
    59: "No response from hardware",
    60: "CAN message not found",
    61: "User CAN receive buffer empty",
    62: "CAN total receive count <> desired count",
    63: "LIN config failed",
    64: "LIN frame number out of range",
    65: "LDF config failed",
    66: "LDF config cmd error",
    67: "TSMaster envrionment not ready",
    68: "reserved failed",
    69: "XL driver error",
    70: "index out of range",
    71: "string length out of range",
    72: "key is not initialized",
    73: "key is wrong",
    74: "write not permitted",
    75: "16 bytes multiple",
    76: "LIN channel out of range",
    77: "DLL not ready",
    78: "Feature not supported",
    79: "common service error",
    80: "read parameter overflow",
    81: "Invalid application channel mapping",
    82: "libTSMaster generic operation failed",
    83: "item already exists",
    84: "item not found",
    85: "logical channel invalid",
    86: "file not exists",
    87: "no init access, cannot set baudrate",
    88: "the channel is inactive",
    89: "the channel is not created",
    90: "length of the appname is out of range",
    91: "project is modified",
    92: "signal not found in database",
    93: "message not found in database",
    94: "TSMaster is not installed",
    95: "Library load failed",
    96: "Library function not found",
    97: 'cannot find libTSMaster.dll, use \"set_libtsmaster_location\" '
        'to set its location before calling initialize_lib_tsmaster',
    98: "PCAN generic operation error",
    99: "Kvaser generic operation error",
    100: "ZLG generic operation error",
    101: "ICS generic operation error",
    102: "TC1005 generic operation error",
    104: "Incorrect system variable type",
    105: "Message not existing, update failed",
    106: "Specified baudrate not available",
    107: "Device does not support sync. transmit",
    108: "Wait time not satisfied",
    109: "Cannot operate while app is connected",
    110: "Create file failed",
    111: "Execute python failed",
    112: "Current multiplexed signal is not active",
    113: "Get handle by logic channel failed",
    114: "Cannot operate while application is Connected, please stop application first",
    115: "File load failed",
    116: "Read LIN Data Failed",
    117: "FIFO not enabled",
    118: "Invalid handle",
    119: "Read file error",
    120: "Read to EOF",
    121: "Configuration not saved",
    122: "IP port open failed",
    123: "TCP connect failed",
    124: "Directory not exists",
    125: "Current library not supported",
    126: "Test is not running",
    127: "Server response not received",
    128: "Create directory failed",
    129: "Invalid argument type",
    130: "Read Data Package from Device Failed",
    131: "Precise replay is running",
    132: "Replay map is already",
    133: "User cancel input",
    134: "API check result is negative",
    135: "CANable generic error",
    136: "Wait criteria not satisfied",
    137: "Operation requires application connected",
    138: "Project path is used by another application",
    139: "Timeout for the sender to transmit data to the receiver",
    140: "Timeout for the receiver to transmit flow control to the sender",
    141: "Timeout for the sender to send first data frame after receiving FC frame",
    142: "Timeout for the receiver to receiving first CF frame after sending FC frame",
    143: "Serial Number Error",
    144: "Invalid flow status of the flow control frame",
    145: "Unexpected Protocol Data Unit",
    146: "Wait counter of the FC frame out of the maxWFT",
    147: "Buffer of the receiver is overflow",
    148: "TP Module is busy",
    149: "There is error from CAN Driver",
    150: "Handle of the TP Module is not exist",
    151: "UDS event buffer is full",
    152: "Handle pool is full, can not add new UDS module",
    153: "Pointer of UDS module is null",
    154: "UDS message is invalid",
    155: "No uds data received",
    156: "Handle of uds is not existing",
    157: "UDS module is not ready",
    158: "Transmit uds frame data failed",
    159: "This uds Service is not supported",
    160: "Time out to send uds request",
    161: "Time out to get uds response",
    162: "Get uds negative response",
    163: "Get uds negative response with expected NRC",
    164: "Get uds negative response with unexpected NRC",
    165: "UDS can tool is not ready",
    166: "UDS data is out of range",
    167: "Get unexpected UDS frame",
    168: "Receive unexpected positive response frame",
    169: "Receive positive response with wrong data",
    170: "Failed to get positive response",
    171: "Reserved UDS Error Code",
    172: "Receive negative response with unexpected NRC",
    173: "UDS service is busy",
    174: "Request download service must be performed before transfer data",
    175: "Length of the uds reponse is wrong",
    176: "Verdict value smaller than specification",
    177: "Verdict value greater than specification",
    178: "Verdict check failed",
    179: "Automation module not loaded, please load it first",
    180: "Panel not found",
    181: "Control not found in panel",
    182: "Panel not loaded, please load it first",
    183: "STIM signal not found",
    184: "Automation sub module not available",
    185: "Automation variant group not found",
    186: "Control not found in panel",
    187: "Panel control does not support this property",
    188: "RBS engine is not running",
    189: "This message does not support PDU container",
    190: "Data not available",
    191: "J1939 not supported",
    192: "Another J1939 PDU is already being transmitted",
    193: "Transmit J1939 PDU failed due to protocol error",
    194: "Transmit J1939 PDU failed due to node inactive",
    195: "API is called without license support",
    196: "Signal range check violation",
    197: "DataLogger read category failed",
    198: "Check Flash Bootloader Version Failed",
    199: "Log file not created",
    200: "Module is being edited by user",
    201: "The Logger device is busy, can not operation at the same time",
    202: "Master node transmit diagnostic package timeout",
    203: "Master node transmit frame failed",
    204: "Master node receive diagnostic package timeout",
    205: "Master node receive frame failed",
    206: "Internal time runs out before reception is completed ",
    207: "Master node received no response ",
    208: "Serial Number Error when receiving multi frames",
    209: "Slave node transmit diagnostic package timeout",
    210: "Slave node receive diagnostic pacakge timeout",
    211: "Slave node transmit frames error",
    212: "Slave node receive frames error",
}
